export const users = [
	{
		id: 1,
		firstName: 'Sherlock',
		lastName: 'Holmes',
		email: 'sherlock.holmes@detective.com',
		birthDate: '1854-01-06',
		address: { city: 'London' },
		phone: '221221221',
		gender: 'M',
	},
	{
		id: 2,
		firstName: 'Luke',
		lastName: 'Skywalker',
		email: 'luke.skywalker@jedi.com',
		birthDate: '1977-05-25',
		address: { city: 'Tatooine' },
		phone: '113113113',
		gender: 'M',
	},
	{
		id: 3,
		firstName: 'Frodo',
		lastName: 'Baggins',
		email: 'frodo.baggins@shire.me',
		birthDate: '2968-09-22',
		address: { city: 'Shire' },
		phone: '141414141',
		gender: 'M',
	},
	{
		id: 4,
		firstName: 'Hermione',
		lastName: 'Granger',
		email: 'hermione.granger@hogwarts.ac.uk',
		birthDate: '1979-09-19',
		address: { city: 'Hogwarts' },
		phone: '987654321',
		gender: 'F',
	},
	{
		id: 5,
		firstName: 'Indiana',
		lastName: 'Jones',
		email: 'indiana.jones@adventurer.com',
		birthDate: '1899-07-01',
		address: { city: 'Marshall College' },
		phone: '123123123',
		gender: 'M',
	},
	{
		id: 6,
		firstName: 'Alice',
		lastName: 'Wonderland',
		email: 'alice.wonderland@rabbit.hole',
		birthDate: '1865-11-26',
		address: { city: 'Wonderland' },
		phone: '777888999',
		gender: 'F',
	},
	{
		id: 7,
		firstName: 'Bruce',
		lastName: 'Wayne',
		email: 'bruce.wayne@wayneenterprises.com',
		birthDate: '1939-05-27',
		address: { city: 'Gotham' },
		phone: '555555555',
		gender: 'M',
	},
	{
		id: 8,
		firstName: 'Clark',
		lastName: 'Kent',
		email: 'clark.kent@dailyplanet.com',
		birthDate: '1938-06-01',
		address: { city: 'Metropolis' },
		phone: '444444444',
		gender: 'M',
	},
	{
		id: 9,
		firstName: 'Tony',
		lastName: 'Stark',
		email: 'tony.stark@starkindustries.com',
		birthDate: '1970-05-29',
		address: { city: 'Malibu' },
		phone: '333333333',
		gender: 'M',
	},
	{
		id: 10,
		firstName: 'Peter',
		lastName: 'Parker',
		email: 'peter.parker@dailybugle.com',
		birthDate: '2001-08-10',
		address: { city: 'Queens' },
		phone: '222222222',
		gender: 'M',
	},
	{
		id: 11,
		firstName: 'Harry',
		lastName: 'Potter',
		email: 'harry.potter@hogwarts.ac.uk',
		birthDate: '1980-07-31',
		address: { city: 'Hogwarts' },
		phone: '777111222',
		gender: 'M',
	},
	{
		id: 12,
		firstName: 'Katniss',
		lastName: 'Everdeen',
		email: 'katniss.everdeen@panem.gov',
		birthDate: '1987-05-08',
		address: { city: 'District 12' },
		phone: '888222333',
		gender: 'F',
	},
	{
		id: 13,
		firstName: 'James',
		lastName: 'Bond',
		email: 'james.bond@mi6.gov.uk',
		birthDate: '1920-11-11',
		address: { city: 'London' },
		phone: '999333444',
		gender: 'M',
	},
	{
		id: 14,
		firstName: 'Arya',
		lastName: 'Stark',
		email: 'arya.stark@winterfell.gov',
		birthDate: '2003-01-29',
		address: { city: 'Winterfell' },
		phone: '666444555',
		gender: 'F',
	},
	{
		id: 15,
		firstName: 'Walter',
		lastName: 'White',
		email: 'walter.white@heisenberg.com',
		birthDate: '1958-09-07',
		address: { city: 'Albuquerque' },
		phone: '555666777',
		gender: 'M',
	},
	{
		id: 16,
		firstName: 'Lara',
		lastName: 'Croft',
		email: 'lara.croft@croftmanor.co.uk',
		birthDate: '1968-02-14',
		address: { city: 'Croft Manor' },
		phone: '444777888',
		gender: 'F',
	},
	{
		id: 17,
		firstName: 'Ellen',
		lastName: 'Ripley',
		email: 'ellen.ripley@nostromo.space',
		birthDate: '2092-01-07',
		address: { city: 'Nostromo' },
		phone: '333888999',
		gender: 'F',
	},
	{
		id: 18,
		firstName: 'John',
		lastName: 'Snow',
		email: 'john.snow@nightswatch.gov',
		birthDate: '0283-12-26',
		address: { city: 'Castle Black' },
		phone: '222999111',
		gender: 'M',
	},
	{
		id: 19,
		firstName: 'Jack',
		lastName: 'Sparrow',
		email: 'jack.sparrow@blackpearl.sea',
		birthDate: '1963-06-09',
		address: { city: 'Caribbean' },
		phone: '111000222',
		gender: 'M',
	},
	{
		id: 20,
		firstName: 'Dorothy',
		lastName: 'Gale',
		email: 'dorothy.gale@oz.gov',
		birthDate: '1922-05-17',
		address: { city: 'Kansas' },
		phone: '123123123',
		gender: 'F',
	},
	{
		id: 21,
		firstName: 'Neo',
		lastName: 'Anderson',
		email: 'neo.anderson@matrix.net',
		birthDate: '1962-03-11',
		address: { city: 'Zion' },
		phone: '321321321',
		gender: 'M',
	},
	{
		id: 22,
		firstName: 'Rick',
		lastName: 'Sanchez',
		email: 'rick.sanchez@multiverse.tv',
		birthDate: '1969-01-22',
		address: { city: 'C-137' },
		phone: '456456456',
		gender: 'M',
	},
	{
		id: 23,
		firstName: 'Elsa',
		lastName: 'Arendelle',
		email: 'elsa.arendelle@frozen.kingdom',
		birthDate: '1821-12-21',
		address: { city: 'Arendelle' },
		phone: '654654654',
		gender: 'F',
	},
	{
		id: 24,
		firstName: 'Tyrion',
		lastName: 'Lannister',
		email: 'tyrion.lannister@casterlyrock.gov',
		birthDate: '1974-06-29',
		address: { city: 'Casterly Rock' },
		phone: '789789789',
		gender: 'M',
	},
	{
		id: 25,
		firstName: 'Cersei',
		lastName: 'Lannister',
		email: 'cersei.lannister@lannister.gov',
		birthDate: '1974-06-29',
		address: { city: 'Casterly Rock' },
		phone: '789789789',
		gender: 'F',
	},
	{
		id: 26,
		firstName: 'Joffrey',
		lastName: 'Baratheon',
		email: 'joffrey.baratheon@dragonstone.gov',
		birthDate: '1974-06-29',
		address: { city: 'Dragonstone' },
		phone: '789789789',
		gender: 'M',
	},
	{
		id: 27,
		firstName: 'Catelyn',
		lastName: 'Stark',
		email: 'catelyn.stark@stark.gov',
		birthDate: '1974-06-29',
		address: { city: 'Winterfell' },
		phone: '789789789',
		gender: 'F',
	},
	{
		id: 28,
		firstName: 'Robb',
		lastName: 'Stark',
		email: 'robb.stark@stark.gov',
		birthDate: '1974-06-29',
		address: { city: 'Winterfell' },
		phone: '789789789',
		gender: 'M',
	},
	{
		id: 29,
		firstName: 'Sansa',
		lastName: 'Stark',
		email: 'sansa.stark@stark.gov',
		birthDate: '1974-06-29',
		address: { city: 'Winterfell' },
		phone: '789789789',
		gender: 'F',
	},
	{
		id: 30,
		firstName: 'Arya',
		lastName: 'Stark',
		email: 'arya.stark@stark.gov',
		birthDate: '1974-06-29',
		address: { city: 'Winterfell' },
		phone: '789789789',
		gender: 'F',
	},
	{
		id: 31,
		firstName: 'Bran',
		lastName: 'Stark',
		email: 'bran.stark@stark.gov',
		birthDate: '1974-06-29',
		address: { city: 'Winterfell' },
		phone: '789789789',
		gender: 'M',
	},
	{
		id: 32,
		firstName: 'Rob',
		lastName: 'Stark',
		email: 'rob.stark@stark.gov',
		birthDate: '1974-06-29',
		address: { city: 'Winterfell' },
		phone: '789789789',
		gender: 'M',
	},
	{
		id: 33,
		firstName: 'Tony',
		lastName: 'Stark',
		email: 'tony.stark@avengers.com',
		birthDate: '1970-05-29',
		address: { city: 'New York' },
		phone: '123456789',
		gender: 'M',
	},
	{
		id: 34,
		firstName: 'Steve',
		lastName: 'Rogers',
		email: 'steve.rogers@avengers.com',
		birthDate: '1918-07-04',
		address: { city: 'Brooklyn' },
		phone: '987654321',
		gender: 'M',
	},
	{
		id: 35,
		firstName: 'Bruce',
		lastName: 'Banner',
		email: 'bruce.banner@avengers.com',
		birthDate: '1969-12-18',
		address: { city: 'Dayton' },
		phone: '456123789',
		gender: 'M',
	},
	{
		id: 36,
		firstName: 'Thor',
		lastName: 'Odinson',
		email: 'thor.odinson@asgard.com',
		birthDate: '965-01-01',
		address: { city: 'Asgard' },
		phone: '789456123',
		gender: 'M',
	},
	{
		id: 37,
		firstName: 'Natasha',
		lastName: 'Romanoff',
		email: 'natasha.romanoff@avengers.com',
		birthDate: '1984-11-22',
		address: { city: 'Stalingrad' },
		phone: '321654987',
		gender: 'F',
	},
	{
		id: 38,
		firstName: 'Clint',
		lastName: 'Barton',
		email: 'clint.barton@avengers.com',
		birthDate: '1971-01-07',
		address: { city: 'Waverly' },
		phone: '159753486',
		gender: 'M',
	},
	{
		id: 39,
		firstName: 'Wanda',
		lastName: 'Maximoff',
		email: 'wanda.maximoff@avengers.com',
		birthDate: '1989-02-10',
		address: { city: 'Sokovia' },
		phone: '357951468',
		gender: 'F',
	},
	{
		id: 40,
		firstName: 'Pietro',
		lastName: 'Maximoff',
		email: 'pietro.maximoff@avengers.com',
		birthDate: '1989-02-10',
		address: { city: 'Sokovia' },
		phone: '753159486',
		gender: 'M',
	},
	{
		id: 41,
		firstName: 'Scott',
		lastName: 'Lang',
		email: 'scott.lang@avengers.com',
		birthDate: '1979-04-04',
		address: { city: 'San Francisco' },
		phone: '951357468',
		gender: 'M',
	},
	{
		id: 42,
		firstName: 'Stephen',
		lastName: 'Strange',
		email: 'stephen.strange@kamar-taj.com',
		birthDate: '1930-11-18',
		address: { city: 'New York' },
		phone: '147258369',
		gender: 'M',
	},
	{
		id: 43,
		firstName: 'Peter',
		lastName: 'Parker',
		email: 'peter.parker@midtownhigh.com',
		birthDate: '2001-08-10',
		address: { city: 'Queens' },
		phone: '369258147',
		gender: 'M',
	},
	{
		id: 44,
		firstName: 'Carol',
		lastName: 'Danvers',
		email: 'carol.danvers@usaf.com',
		birthDate: '1968-04-01',
		address: { city: 'Boston' },
		phone: '789321654',
		gender: 'F',
	},
	{
		id: 45,
		firstName: 'TChalla',
		lastName: 'Wakanda',
		email: 'tchalla.wakanda@wakanda.com',
		birthDate: '1977-07-19',
		address: { city: 'Wakanda' },
		phone: '654987321',
		gender: 'M',
	},
	{
		id: 46,
		firstName: 'Nick',
		lastName: 'Fury',
		email: 'nick.fury@shield.com',
		birthDate: '1950-12-21',
		address: { city: 'New York' },
		phone: '987321654',
		gender: 'M',
	},
	{
		id: 47,
		firstName: 'Sam',
		lastName: 'Wilson',
		email: 'sam.wilson@avengers.com',
		birthDate: '1978-09-23',
		address: { city: 'Harlem' },
		phone: '321987654',
		gender: 'M',
	},
];
